export const GET_RESTAURANTS_BEGIN = "GET_RESTAURANTS_BEGIN";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE";
export const SELECT_RESTAURANT = "SELECT_RESTAURANT";
